### ISSUE TITLE
JSON representation for tuples

### ISSUE THREAD

**Issue by paulvi** [Olical/tuple#6]
As creator of JS tuples library, can you recommend JSON representation for tuples (e.g. array vs object)

ref https://github.com/FasterXML/jackson-databind/issues/2020#issuecomment-386940529

**Comment by Olical** [comment]
JVM languages only really worry about one runtime, _the_ JVM, whereas JavaScript can be running on almost any implementation and any device on the planet. For that reason, I think this is something you'll need to benchmark on whatever you will be targeting, I'll just be guessing otherwise.

If I _had_ to guess, I'd say objects since arrays are almost a superset of objects, but I honestly don't know for sure. Try some things out, but I think you'll find almost no difference between the two.

My recommendation would be to just go with arrays and be done with it, it'll be much easier. You'll find arrays faster on some platforms and objects faster on others, it depends on how they were built.

I hope this helps!

**Comment by paulvi** [comment]
Thanks, there was even quick test via https://jsperf.com/array-vs-object-tuple

Arrays win.

![](https://user-images.githubusercontent.com/1614482/39689510-9f13bfe8-5209-11e8-89dd-59da8c4d86e9.png)

Other aspect is, what is default serialization into JSON for languages that do have tuples...
But again array is less ambiguous.

Have a nice day.

**Comment by Olical** [comment]
Just bear in mind that you're testing in one specific JavaScript runtime, I wouldn't be surprised in the slightest if the results differed in node / rhino / chrome / safari / opera / IE etc :smile:

I think you can just go with arrays since they seem fine and make sense as a tuple. Generally if you're serialising that sort of type and you want to be able to deserialise it back to it's original type you'll have to tag it with some auxiliary type data or use a better serialisation format that allows extension.

**Comment by Olical** [comment]
Gonna close this for now since I think you've solved your question? The rest seems a little unrelated to this library itself. I don't think I have anything to contribute to the question either. Best of luck!

**Comment by paulvi** [comment]
Sure, thanks

Well, can README have export to JSON and JSON example?
